name: pdf build
on:
  push:
    branches-ignore:
      - 'gh-action-result/pdf-files'
jobs:
  build_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y curl
          curl -sL https://deb.nodesource.com/setup_20.x -o /tmp/nodesource_setup.sh
          curl -sL https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -o /tmp/google-chrome-stable_current_amd64.deb
          sudo bash /tmp/nodesource_setup.sh
          sudo apt-get install -y nodejs /tmp/google-chrome-stable_current_amd64.deb
          npm install mdpdf@3.0.2 pdf-lib@1.17.1 path@0.12.7 commander@7.2.0
      - name: Compile PDF document
        run: |
          node ./convert.mjs -i draft.md -o draft.pdf
#      - name: Commit to orphan branch
#        run: |
#          git checkout --orphan gh-action-result/pdf-files
#          git rm -rf .
#          git add /home/pptruser/draft.pdf
#          git -c user.name='GitHub Action' -c user.email='action@github.com' commit -m "Built PDF document"
#      - name: Push changes
#        uses: ad-m/github-push-action@master
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          branch: gh-action-result/pdf-files
#          force: true

